/**:
  ros__parameters:
    input_offset_ms: [0.0]
    timeout_ms: 70.0
    match_threshold_ms: 50.0
    image_buffer_size: 15
    debug_mode: false
    filter_scope_min_x: -300.0
    filter_scope_min_y: -200.0
    filter_scope_min_z: -200.0
    filter_scope_max_x: 300.0
    filter_scope_max_y: 200.0
    filter_scope_max_z: 200.0
